/**
 * Advisory banner — persistent, non-dismissible status strip above the
 * conflict banner.
 *
 * Used for sticky context the user must keep seeing:
 *
 *   - ``kind: "generated"`` — the active corpus is regenerated by
 *     attune-author and edits will be overwritten on regen.
 *   - ``kind: "duplicate_session"`` — another tab already owns this
 *     ``(corpus, path)`` key; this tab is read-only.
 *
 * The host owns one banner element per shell. ``setAdvisories`` does
 * a full replace each call so callers can flip messages on/off
 * without manual diffing.
 */

export type AdvisoryKind = "generated" | "duplicate_session";

export interface Advisory {
  kind: AdvisoryKind;
  /** Plain-text message — shown verbatim. */
  message: string;
}

export function setAdvisories(
  parent: HTMLElement,
  advisories: readonly Advisory[],
): void {
  parent.innerHTML = "";
  if (advisories.length === 0) {
    parent.hidden = true;
    return;
  }
  parent.hidden = false;
  for (const a of advisories) {
    const row = document.createElement("div");
    row.className = `attune-advisory attune-advisory-${a.kind}`;
    row.dataset.kind = a.kind;
    const icon = document.createElement("span");
    icon.className = "attune-advisory-icon";
    icon.textContent = a.kind === "generated" ? "⚙" : "👀";
    icon.setAttribute("aria-hidden", "true");
    const msg = document.createElement("span");
    msg.className = "attune-advisory-msg";
    msg.textContent = a.message;
    row.appendChild(icon);
    row.appendChild(msg);
    parent.appendChild(row);
  }
}

export const GENERATED_CORPUS_MESSAGE =
  "This corpus is regenerated by attune-author. Edits made here will be overwritten on the next regen.";

export const DUPLICATE_SESSION_MESSAGE =
  "Another tab is editing this file. This tab is read-only — close it or close the other tab to take over.";
