/**
 * Staleness status row + provenance panel + "Regenerate from source"
 * button (specs/hash-regenerate-button).
 *
 * Read path: GET .../template/provenance drives a 4-state status row
 * (fresh / stale / unbound / sources_missing). Write path: the button
 * POSTs .../template/regenerate, which starts a job; the file rewrite
 * propagates to the editor through the existing `file_changed` WS event.
 * The host calls `refresh()` after that reload to flip the row green.
 */

import type { EditorApi, Provenance, ProvenanceStatus } from "./api";

export interface ProvenancePanelOptions {
  host: HTMLElement;
  api: EditorApi;
  corpusId: string;
  relPath: string;
  /** Surface a message to the user (reuses the editor toast). */
  onToast?: (msg: string, kind?: "ok" | "err") => void;
}

export interface ProvenancePanelHandle {
  /** Re-fetch provenance and re-render (call after a reload). */
  refresh(): void;
}

const STATUS_LABEL: Record<ProvenanceStatus, string> = {
  fresh: "Hash matches source",
  stale: "Stale — source has changed since last regen",
  unbound: "Not generated by attune-author",
  sources_missing: "Source files missing — regenerate would fail",
};

export function mountProvenancePanel(opts: ProvenancePanelOptions): ProvenancePanelHandle {
  const { host, api, corpusId, relPath, onToast } = opts;
  host.innerHTML = "";
  host.className = "attune-prov";

  const row = document.createElement("div");
  row.className = "attune-prov-row";
  const dot = document.createElement("span");
  dot.className = "attune-prov-dot attune-prov-dot-loading";
  const label = document.createElement("span");
  label.className = "attune-prov-label";
  label.textContent = "Checking source…";
  row.appendChild(dot);
  row.appendChild(label);

  const regenBtn = document.createElement("button");
  regenBtn.type = "button";
  regenBtn.className = "attune-btn attune-btn-secondary attune-prov-regen";
  regenBtn.textContent = "Regenerate from source";
  regenBtn.hidden = true;
  row.appendChild(regenBtn);

  const details = document.createElement("details");
  details.className = "attune-prov-details";
  const summary = document.createElement("summary");
  summary.textContent = "Provenance";
  const dl = document.createElement("dl");
  dl.className = "attune-prov-dl";
  details.appendChild(summary);
  details.appendChild(dl);
  details.hidden = true;

  host.appendChild(row);
  host.appendChild(details);

  let polling = false;

  function setDot(status: ProvenanceStatus | "loading" | "error"): void {
    dot.className = `attune-prov-dot attune-prov-dot-${status}`;
  }

  function row2(term: string, value: string): void {
    const dt = document.createElement("dt");
    dt.textContent = term;
    const dd = document.createElement("dd");
    dd.textContent = value;
    dl.appendChild(dt);
    dl.appendChild(dd);
  }

  function renderDetails(p: Provenance): void {
    dl.innerHTML = "";
    if (p.feature) row2("feature", p.feature);
    if (p.depth) row2("depth", p.depth);
    if (p.generated_at) row2("generated", p.generated_at);
    if (p.stored_hash) row2("stored hash", p.stored_hash);
    if (p.current_hash) row2("source hash", p.current_hash);
    if (p.source_globs.length) row2("source globs", p.source_globs.join(", "));
    if (p.source_files.length) {
      row2("source files", `${p.source_files.length} file(s)`);
      const dd = dl.lastElementChild as HTMLElement;
      dd.title = p.source_files.join("\n");
    }
    details.hidden = dl.childElementCount === 0;
  }

  function render(p: Provenance): void {
    setDot(p.status);
    label.textContent = STATUS_LABEL[p.status];
    if (p.status === "unbound" || p.status === "sources_missing") {
      label.title = p.reason ?? "";
    } else {
      label.removeAttribute("title");
    }
    regenBtn.hidden = !p.can_regenerate;
    regenBtn.disabled = !p.can_regenerate;
    renderDetails(p);
  }

  async function refresh(): Promise<void> {
    try {
      const p = await api.getProvenance(corpusId, relPath);
      render(p);
    } catch {
      setDot("error");
      label.textContent = "Provenance unavailable";
      regenBtn.hidden = true;
      details.hidden = true;
    }
  }

  async function pollJob(jobId: string): Promise<void> {
    if (polling) return;
    polling = true;
    try {
      for (let i = 0; i < 600; i++) {
        await new Promise((r) => setTimeout(r, 1000));
        let job;
        try {
          job = await api.getJob(jobId);
        } catch {
          break; // job trimmed or transient error — fall back to a refresh
        }
        if (job.status === "completed") {
          // The file_changed reload usually beats us here; refresh anyway.
          await refresh();
          onToast?.("Regenerate complete.");
          return;
        }
        if (job.status === "errored" || job.status === "cancelled") {
          setDot("error");
          label.textContent = `Last regen ${job.status} — see job`;
          regenBtn.disabled = false;
          regenBtn.textContent = "Regenerate from source";
          onToast?.(job.error ?? `Regenerate ${job.status}.`, "err");
          return;
        }
      }
    } finally {
      polling = false;
    }
  }

  regenBtn.addEventListener("click", async () => {
    regenBtn.disabled = true;
    regenBtn.textContent = "Regenerating…";
    setDot("loading");
    label.textContent = "Regenerating from source…";
    try {
      const job = await api.regenerateTemplate(corpusId, relPath);
      onToast?.("Regenerating — running as a background job.");
      void pollJob(job.id);
    } catch (err) {
      regenBtn.disabled = false;
      regenBtn.textContent = "Regenerate from source";
      onToast?.(`Regenerate failed: ${(err as Error).message}`, "err");
      void refresh();
    }
  });

  void refresh();

  return {
    refresh() {
      void refresh();
    },
  };
}
